//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kk
{
    using System;
    using System.Collections.Generic;
    
    public partial class DenemeUser
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Yaş { get; set; }
        public string Telno { get; set; }
        public string Adres { get; set; }
    }
}
